# Generated by Django 5.2.5 on 2025-09-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
